const mongoose=require('mongoose')
const {Schema}=mongoose;
const userSchema= new Schema ({
    firstName:{
        type:String,
        required:true,
        minLength:3,
        maxLength:20
    },
    lastName:{
        type:String,
        required:true,
        minLength:3,
        maxLength:20
    }
    ,
    email:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        lowercase:true,
        immuatable:true
    },
    age:{
        type:Number,
        min:6,
        max:80,
        required:true
    },
    role:{
        type:String,
        enum:["user","admin"],
        default:"user"
    },
    problemSolved:{
        type:[String]
    },
    password:{
        type:String,
        required:true,
        minLength:4,
        maxLength:20
    }
},
{
    timestamps:true
})
const User=mongoose.model("users",userSchema);
module.exports=User;